###

POST localhost:8080/delivery/auth?login=courier&password=courier

###

PUT localhost:8080/delivery/changeToDelivered?phoneNumber=375293575921

###

PUT localhost:8080/delivery/changeAllToDelivered

###

PUT localhost:8080/delivery/changeToInProcess?phoneNumber=375293575921

###

PUT localhost:8080/delivery/changeAllToInProcess

###
///
PUT localhost:8080/delivery/createOrder?serialNumber=123478
Content-Type: application/json

{
  "login": "isethesal",
  "password": "12345",
  "name": "Ilea",
  "phoneNumber": "375293575921"
}

###

PUT localhost:8080/delivery/addToOrder?phoneNumber=375293575921&serialNumber=1234

###

PUT localhost:8080/delivery/changeUserNumber?phoneNumber=375293575921&newPhoneNumber=+375290003333

###

GET localhost:8080/delivery/getOrder?phoneNumber=375293575921

###

DELETE localhost:8080/delivery/removeFromOrder?phoneNumber=375293575921&serialNumber=1234

###

DELETE localhost:8080/delivery/deleteOrder?phoneNumber=375293575921

###
